import type { SeoMetaBlock } from "./seoTypes";

/**
 * Off-page SEO only: titles/descriptions for `<head>`, OG/Twitter, and JSON-LD — not `site-content.json` body copy.
 * Homepage uses brand `<title>` from `buildRootMetadata`; put query phrases in `metaDescription` (and `getSeoRootDescription`).
 */
export const seoMetaBlocks: SeoMetaBlock[] = [
  {
    id: "hpaa-overview",
    title: "What Is a High Performance Autonomous Aircraft (HPAA)?",
    metaTitle: "HPAA — High Performance Autonomous Aircraft | Robot Aircraft Germany",
    metaDescription:
      "HPAA — High Performance Autonomous Aircraft. Robot aircraft Germany: KUM Services GmbH converts civil platforms into HPAA for ISR, cargo, strike & special missions. EASA Part-145 certified.",
    targetKeywords: [
      "HPAA",
      "hpaa",
      "aircraft robot",
      "robot aircraft",
      "high performance autonomous aircraft",
      "autonomous aircraft conversion",
      "civil aircraft conversion",
      "KUM Services GmbH",
      "KUM Services",
    ],
  },
  {
    id: "hpaa-vs-purpose-built",
    title: "Why Convert a Civil Aircraft Instead of Buying a Purpose-Built UAV?",
    metaTitle: "Civil Aircraft to Autonomous Platform Germany | HPAA Conversion",
    metaDescription:
      "Civil aircraft to autonomous platform Germany — KUM Services GmbH converts civil aircraft into HPAA autonomous platforms faster and at lower cost than purpose-built UAV programmes.",
    targetKeywords: [
      "civil aircraft to autonomous platform Germany",
      "civil aircraft to autonomous platform",
      "civil aircraft conversion Germany",
      "civil aircraft conversion",
      "manned to unmanned conversion Germany",
      "affordable autonomous aircraft",
      "fast aircraft conversion",
      "rapid fielding aircraft",
      "manned to unmanned conversion",
      "HPAA vs UAV",
      "autonomous aircraft supplier",
    ],
  },
  {
    id: "payload-delivery-aircraft",
    title: "Autonomous Payload Delivery: From Cargo Resupply to Precision Strike",
    metaTitle: "Autonomous Payload Delivery Aircraft | HPAA Platforms",
    metaDescription:
      "KUM Services HPAA platforms deliver payloads autonomously — from cargo and aerial resupply to precision munitions and kinetic effects. Configurable for any mission profile.",
    targetKeywords: [
      "payload delivery aircraft",
      "autonomous payload delivery",
      "precision payload drop",
      "combat payload aircraft",
      "kinetic effects platform",
      "aerial resupply unmanned",
      "parachute payload drop",
      "PGM delivery",
      "loitering munition carrier",
      "autonomous bomb drop",
      "attritable aircraft",
    ],
  },
  {
    id: "isr-surveillance-aircraft",
    title: "Autonomous ISR Aircraft: Persistent Surveillance Without the Cost",
    metaTitle: "Autonomous ISR Surveillance Aircraft | HPAA Germany",
    metaDescription:
      "HPAA platforms from KUM Services deliver persistent ISR, SIGINT, SAR and EO/IR surveillance at a fraction of the cost of purpose-built systems. Global support included.",
    targetKeywords: [
      "ISR aircraft",
      "surveillance aircraft",
      "intelligence surveillance reconnaissance",
      "SIGINT platform",
      "SAR integration",
      "EO/IR sensor integration",
      "airborne surveillance",
      "border surveillance aircraft",
      "maritime patrol aircraft",
      "special mission aircraft",
      "affordable ISR platform",
    ],
  },
  {
    id: "counter-uas-aircraft",
    title: "Airborne Counter-UAS: Defeating Drone Threats with HPAA Platforms",
    metaTitle: "Counter-UAS Aircraft | Airborne Drone Defeat | HPAA",
    metaDescription:
      "KUM Services HPAA platforms provide kinetic and electronic counter-UAS capability against drone swarms and individual UAS threats. Faster, higher, further than ground-based C-UAS.",
    targetKeywords: [
      "counter-UAS aircraft",
      "counter-drone aircraft",
      "C-UAS platform",
      "anti-drone platform",
      "UAS defeat",
      "drone interception aircraft",
      "kinetic counter-drone",
      "airborne counter-UAS",
      "drone swarm defeat",
    ],
  },
  {
    id: "hpaa-platform-guide",
    title: "Choosing the Right HPAA Platform: From PC-12 to C-130J",
    metaTitle: "HPAA Platform Guide: King Air, PC-12, C-130 & More",
    metaDescription:
      "Compare HPAA and aircraft robot-capable platforms — King Air 350, Pilatus PC-12, Cessna 208, Citation 525B and C-130J. Mission-ready integration for ISR, cargo or strike.",
    targetKeywords: [
      "King Air 350",
      "Pilatus PC-12",
      "Cessna 208",
      "Cessna Citation 525",
      "C-130J",
      "turboprop ISR platform",
      "business jet conversion",
      "special mission aircraft",
      "HPAA platform provider",
      "aircraft robot",
    ],
  },
  {
    id: "autonomous-flight-control",
    title: "Autonomous Flight Control Systems for HPAA Platforms",
    metaTitle: "Autonomous Flight Control & AI Systems for HPAA Aircraft",
    metaDescription:
      "KUM Services integrates advanced autonomous flight control, AI targeting, BVLOS datalinks and GCS systems into HPAA platforms. University of Stuttgart flight control partner.",
    targetKeywords: [
      "autonomous flight control",
      "flight control system",
      "AI flight control",
      "autonomous mission planning",
      "BVLOS operations",
      "beyond visual line of sight",
      "ground control station",
      "datalink integration",
      "GCS",
      "target acquisition system",
      "autonomous targeting",
    ],
  },
  {
    id: "defence-procurement-hpaa",
    title: "Procuring an HPAA: A Guide for Defence and Government Buyers",
    metaTitle: "HPAA Defence Procurement Guide | KUM Services Germany",
    metaDescription:
      "A practical guide for defence ministries, government agencies and NATO forces procuring an HPAA autonomous aircraft. Fast fielding, low cost, EASA-certified. Request a proposal.",
    targetKeywords: [
      "defence procurement",
      "defense procurement",
      "buy autonomous aircraft",
      "HPAA manufacturer",
      "HPAA supplier",
      "NATO UAS",
      "NATO autonomous systems",
      "rapid capability acquisition",
      "RFP autonomous aircraft",
      "turnkey UAV solution",
      "autonomous aircraft quote",
      "military aircraft conversion",
    ],
  },
  {
    id: "unmanned-aircraft-germany",
    title: "Unmanned Aircraft Germany: Civil Aircraft to UAS Conversion",
    metaTitle: "Unmanned Aircraft Germany | Civil Aircraft to UAS — KUM Services GmbH",
    metaDescription:
      "Unmanned aircraft Germany — KUM Services GmbH converts civil turboprop and turbofan aircraft into unmanned autonomous platforms (UAS) for ISR, cargo, strike and special missions. EASA Part-145 certified.",
    targetKeywords: [
      "unmanned aircraft Germany",
      "unmanned aircraft conversion Germany",
      "manned to unmanned conversion Germany",
      "UAV conversion Germany",
      "civil aircraft to UAS Germany",
      "remotely piloted aircraft Germany",
      "optionally piloted aircraft Germany",
    ],
  },
  {
    id: "drone-aircraft-conversion-germany",
    title: "Drone Aircraft Conversion Germany: Civil to High-Performance Drone",
    metaTitle: "Drone Aircraft Conversion Germany | Civil to Drone — KUM Services GmbH",
    metaDescription:
      "Drone aircraft conversion Germany — KUM Services GmbH converts civil turboprop and turbofan aircraft into high-performance drone platforms for ISR, cargo, strike and special missions. EASA Part-145 certified.",
    targetKeywords: [
      "drone aircraft conversion Germany",
      "drone conversion Germany",
      "civil aircraft to drone Germany",
      "aircraft drone conversion Germany",
      "convert aircraft to drone Germany",
      "drone platform conversion Germany",
      "UAV conversion Germany",
    ],
  },
  {
    id: "high-performance-combat-drones-germany",
    title: "High-Performance Combat Drones Germany: Civil Aircraft for Strike Missions",
    metaTitle: "High-Performance Combat Drones Germany | UCAV — KUM Services GmbH",
    metaDescription:
      "High-performance combat drones Germany — KUM Services GmbH converts proven civil aircraft into combat drone platforms for strike, ISR and special missions. Faster and lower cost than purpose-built UCAV programmes.",
    targetKeywords: [
      "high-performance combat drones Germany",
      "combat drones Germany",
      "combat drone Germany",
      "high performance combat drone Germany",
      "strike drone Germany",
      "UCAV Germany",
      "unmanned combat aerial vehicle Germany",
      "armed drone Germany",
    ],
  },
  {
    id: "autonomous-platform-aircraft-germany",
    title: "Autonomous Platform Aircraft Germany: Multi-Role Civil Aircraft Conversion",
    metaTitle: "Autonomous Platform Aircraft Germany | HPAA — KUM Services GmbH",
    metaDescription:
      "Autonomous platform aircraft Germany — KUM Services GmbH converts proven civil aircraft into autonomous platform aircraft for ISR, cargo, strike and special missions. EASA Part-145 certified.",
    targetKeywords: [
      "autonomous platform aircraft Germany",
      "autonomous aircraft platform Germany",
      "civil aircraft to autonomous platform Germany",
      "autonomous platform Germany",
      "HPAA platform Germany",
      "optionally piloted aircraft platform Germany",
    ],
  },
  {
    id: "hpaa-faq",
    title: "Frequently Asked Questions: HPAA and Autonomous Aircraft Conversion",
    metaTitle: "HPAA FAQ — Autonomous Aircraft Conversion Questions Answered",
    metaDescription:
      "Answers to the most common questions about HPAA conversion, platform selection, mission capability, EASA certification, and procurement. KUM Services GmbH (Germany).",
    targetKeywords: [
      "HPAA",
      "autonomous aircraft conversion",
      "how to convert civil aircraft to UAV",
      "EASA Part-145",
      "special mission aircraft for sale",
      "civil aircraft to autonomous platform",
      "aircraft conversion company Europe",
    ],
  },
  {
    id: "easa-part-145-mro",
    title: "EASA Part-145 MRO and Aircraft Maintenance in Germany",
    metaTitle: "EASA Part-145 MRO Germany | Aircraft Maintenance — KUM Services GmbH",
    metaDescription:
      "EASA Part-145 aircraft MRO Germany — KUM Services GmbH programmes with Part One-Forty Five GmbH for certified maintenance, modification, and special mission conversion on civil turboprop and turbofan platforms.",
    targetKeywords: [
      "EASA Part 145 maintenance organisation Germany",
      "EASA Part-145 MRO Germany",
      "aircraft MRO Germany",
      "aircraft maintenance repair overhaul Germany",
      "EASA Part 145 MRO Lake Constance",
      "aircraft modification company Baden-Württemberg",
      "EASA certified aircraft maintenance",
      "MRO partner Germany",
      "Part One-Forty Five GmbH",
      "Neuhausen ob Eck",
    ],
  },
  {
    id: "aircraft-avionics-retrofit",
    title: "Aircraft Avionics Retrofit and Mission Systems Integration",
    metaTitle: "Aircraft Avionics Retrofit Germany | Mission Systems — KUM Services GmbH",
    metaDescription:
      "Aircraft avionics retrofit and mission systems integration Germany — flight control, datalinks, EO/IR and ISR sensor installation on civil platforms. EASA Part-145 partner network.",
    targetKeywords: [
      "aircraft avionics retrofit",
      "avionics integration aircraft",
      "mission systems integration Germany",
      "EO/IR sensor installation aircraft",
      "ISR sensor integration aircraft",
      "flight control system integration",
      "datalink integration aircraft",
      "autopilot integration",
      "special mission avionics",
      "aircraft retrofit Germany",
    ],
  },
  {
    id: "special-mission-conversion",
    title: "Special Mission Aircraft Conversion in Germany",
    metaTitle: "Special Mission Aircraft Conversion Germany | Surveillance — KUM Services GmbH",
    metaDescription:
      "Special mission aircraft conversion Germany — civil turboprop and business jet platforms configured for surveillance, ISR, and government mission systems. EASA Part-145 certified modification partner.",
    targetKeywords: [
      "special mission aircraft conversion",
      "special mission aircraft modification Europe",
      "surveillance aircraft conversion",
      "civil aircraft special mission conversion",
      "convert business jet for surveillance",
      "ISR aircraft conversion Germany",
      "government mission aircraft modification",
      "aircraft STC modification Germany",
      "special mission integrator Germany",
    ],
  },
  {
    id: "mro-contact-enquiry",
    title: "Contact KUM Services — MRO, Modification and HPAA Enquiries",
    metaTitle: "Contact KUM Services GmbH | MRO & Aircraft Modification Germany",
    metaDescription:
      "Contact KUM Services GmbH for EASA Part-145 MRO, aircraft modification, avionics integration, special mission conversion, and HPAA programme proposals. Confidential enquiries welcome.",
    targetKeywords: [
      "aircraft modification enquiry Germany",
      "EASA Part-145 MRO contact",
      "special mission aircraft quote",
      "avionics retrofit quote",
      "aircraft conversion proposal",
      "KUM Services GmbH contact",
      "autonomous aircraft quote",
    ],
  },
];
