import type { SeoMetaBlock } from "./seoTypes";

/**
 * Off-page SEO only: titles/descriptions for `<head>`, OG/Twitter, and JSON-LD — not `site-content.json` body copy.
 * Homepage uses brand `<title>` from `buildRootMetadata`; put query phrases in `metaDescription` (and `getSeoRootDescription`).
 */
export const seoMetaBlocks: SeoMetaBlock[] = [
  {
    id: "hpaa-overview",
    title: "What Is a High Performance Autonomous Aircraft (HPAA)?",
    metaTitle: "HPAA — High Performance Autonomous Aircraft | Robot Aircraft Germany",
    metaDescription:
      "HPAA — High Performance Autonomous Aircraft. Robot aircraft Germany: KUM Services GmbH, Konstanz converts civil platforms into HPAA for ISR, cargo, strike & special missions. EASA Part-145 certified.",
    targetKeywords: [
      "aircraft robot Konstanz",
      "robot aircraft Konstanz",
      "HPAA",
      "hpaa",
      "aircraft robot",
      "robot aircraft",
      "high performance autonomous aircraft",
      "autonomous aircraft conversion",
      "civil aircraft conversion",
      "KUM Services GmbH",
      "KUM Services Konstanz",
    ],
  },
  {
    id: "hpaa-vs-purpose-built",
    title: "Why Convert a Civil Aircraft Instead of Buying a Purpose-Built UAV?",
    metaTitle: "Civil Aircraft to Autonomous Platform Germany | HPAA Conversion",
    metaDescription:
      "Civil aircraft to autonomous platform Germany — KUM Services GmbH, Konstanz converts civil aircraft into HPAA autonomous platforms faster and at lower cost than purpose-built UAV programmes.",
    targetKeywords: [
      "civil aircraft to autonomous platform Germany",
      "civil aircraft to autonomous platform",
      "civil aircraft conversion Germany",
      "civil aircraft conversion",
      "manned to unmanned conversion Germany",
      "affordable autonomous aircraft",
      "fast aircraft conversion",
      "rapid fielding aircraft",
      "manned to unmanned conversion",
      "HPAA vs UAV",
      "autonomous aircraft supplier",
    ],
  },
  {
    id: "payload-delivery-aircraft",
    title: "Autonomous Payload Delivery: From Cargo Resupply to Precision Strike",
    metaTitle: "Autonomous Payload Delivery Aircraft | HPAA Platforms",
    metaDescription:
      "KUM Services HPAA platforms deliver payloads autonomously — from cargo and aerial resupply to precision munitions and kinetic effects. Configurable for any mission profile.",
    targetKeywords: [
      "payload delivery aircraft",
      "autonomous payload delivery",
      "precision payload drop",
      "combat payload aircraft",
      "kinetic effects platform",
      "aerial resupply unmanned",
      "parachute payload drop",
      "PGM delivery",
      "loitering munition carrier",
      "autonomous bomb drop",
      "attritable aircraft",
    ],
  },
  {
    id: "isr-surveillance-aircraft",
    title: "Autonomous ISR Aircraft: Persistent Surveillance Without the Cost",
    metaTitle: "Autonomous ISR Surveillance Aircraft | HPAA Germany",
    metaDescription:
      "HPAA platforms from KUM Services deliver persistent ISR, SIGINT, SAR and EO/IR surveillance at a fraction of the cost of purpose-built systems. Global support included.",
    targetKeywords: [
      "ISR aircraft",
      "surveillance aircraft",
      "intelligence surveillance reconnaissance",
      "SIGINT platform",
      "SAR integration",
      "EO/IR sensor integration",
      "airborne surveillance",
      "border surveillance aircraft",
      "maritime patrol aircraft",
      "special mission aircraft",
      "affordable ISR platform",
    ],
  },
  {
    id: "counter-uas-aircraft",
    title: "Airborne Counter-UAS: Defeating Drone Threats with HPAA Platforms",
    metaTitle: "Counter-UAS Aircraft | Airborne Drone Defeat | HPAA",
    metaDescription:
      "KUM Services HPAA platforms provide kinetic and electronic counter-UAS capability against drone swarms and individual UAS threats. Faster, higher, further than ground-based C-UAS.",
    targetKeywords: [
      "counter-UAS aircraft",
      "counter-drone aircraft",
      "C-UAS platform",
      "anti-drone platform",
      "UAS defeat",
      "drone interception aircraft",
      "kinetic counter-drone",
      "airborne counter-UAS",
      "drone swarm defeat",
    ],
  },
  {
    id: "hpaa-platform-guide",
    title: "Choosing the Right HPAA Platform: From PC-12 to C-130J",
    metaTitle: "HPAA Platform Guide: King Air, PC-12, C-130 & More",
    metaDescription:
      "Compare HPAA and aircraft robot-capable platforms — King Air 350, Pilatus PC-12, Cessna 208, Citation 525B and C-130J. Konstanz-based integration for ISR, cargo or strike.",
    targetKeywords: [
      "King Air 350",
      "Pilatus PC-12",
      "Cessna 208",
      "Cessna Citation 525",
      "C-130J",
      "turboprop ISR platform",
      "business jet conversion",
      "special mission aircraft",
      "HPAA platform provider",
      "aircraft robot",
      "HPAA Konstanz",
    ],
  },
  {
    id: "autonomous-flight-control",
    title: "Autonomous Flight Control Systems for HPAA Platforms",
    metaTitle: "Autonomous Flight Control & AI Systems for HPAA Aircraft",
    metaDescription:
      "KUM Services integrates advanced autonomous flight control, AI targeting, BVLOS datalinks and GCS systems into HPAA platforms. University of Stuttgart flight control partner.",
    targetKeywords: [
      "autonomous flight control",
      "flight control system",
      "AI flight control",
      "autonomous mission planning",
      "BVLOS operations",
      "beyond visual line of sight",
      "ground control station",
      "datalink integration",
      "GCS",
      "target acquisition system",
      "autonomous targeting",
    ],
  },
  {
    id: "defence-procurement-hpaa",
    title: "Procuring an HPAA: A Guide for Defence and Government Buyers",
    metaTitle: "HPAA Defence Procurement Guide | KUM Services Germany",
    metaDescription:
      "A practical guide for defence ministries, government agencies and NATO forces procuring an HPAA autonomous aircraft. Fast fielding, low cost, EASA-certified. Request a proposal.",
    targetKeywords: [
      "defence procurement",
      "defense procurement",
      "buy autonomous aircraft",
      "HPAA manufacturer",
      "HPAA supplier",
      "NATO UAS",
      "NATO autonomous systems",
      "rapid capability acquisition",
      "RFP autonomous aircraft",
      "turnkey UAV solution",
      "autonomous aircraft quote",
      "military aircraft conversion",
    ],
  },
  {
    id: "unmanned-aircraft-germany",
    title: "Unmanned Aircraft Germany: Civil Aircraft to UAS Conversion",
    metaTitle: "Unmanned Aircraft Germany | Civil Aircraft to UAS — KUM Services GmbH",
    metaDescription:
      "Unmanned aircraft Germany — KUM Services GmbH, Konstanz converts civil turboprop and turbofan aircraft into unmanned autonomous platforms (UAS) for ISR, cargo, strike and special missions. EASA Part-145 certified.",
    targetKeywords: [
      "unmanned aircraft Germany",
      "unmanned aircraft conversion Germany",
      "manned to unmanned conversion Germany",
      "UAV conversion Germany",
      "civil aircraft to UAS Germany",
      "remotely piloted aircraft Germany",
      "optionally piloted aircraft Germany",
    ],
  },
  {
    id: "drone-aircraft-conversion-germany",
    title: "Drone Aircraft Conversion Germany: Civil to High-Performance Drone",
    metaTitle: "Drone Aircraft Conversion Germany | Civil to Drone — KUM Services GmbH",
    metaDescription:
      "Drone aircraft conversion Germany — KUM Services GmbH, Konstanz converts civil turboprop and turbofan aircraft into high-performance drone platforms for ISR, cargo, strike and special missions. EASA Part-145 certified.",
    targetKeywords: [
      "drone aircraft conversion Germany",
      "drone conversion Germany",
      "civil aircraft to drone Germany",
      "aircraft drone conversion Germany",
      "convert aircraft to drone Germany",
      "drone platform conversion Germany",
      "UAV conversion Germany",
    ],
  },
  {
    id: "high-performance-combat-drones-germany",
    title: "High-Performance Combat Drones Germany: Civil Aircraft for Strike Missions",
    metaTitle: "High-Performance Combat Drones Germany | UCAV — KUM Services GmbH",
    metaDescription:
      "High-performance combat drones Germany — KUM Services GmbH, Konstanz converts proven civil aircraft into combat drone platforms for strike, ISR and special missions. Faster and lower cost than purpose-built UCAV programmes.",
    targetKeywords: [
      "high-performance combat drones Germany",
      "combat drones Germany",
      "combat drone Germany",
      "high performance combat drone Germany",
      "strike drone Germany",
      "UCAV Germany",
      "unmanned combat aerial vehicle Germany",
      "armed drone Germany",
    ],
  },
  {
    id: "autonomous-platform-aircraft-germany",
    title: "Autonomous Platform Aircraft Germany: Multi-Role Civil Aircraft Conversion",
    metaTitle: "Autonomous Platform Aircraft Germany | HPAA — KUM Services GmbH",
    metaDescription:
      "Autonomous platform aircraft Germany — KUM Services GmbH, Konstanz converts proven civil aircraft into autonomous platform aircraft for ISR, cargo, strike and special missions. EASA Part-145 certified.",
    targetKeywords: [
      "autonomous platform aircraft Germany",
      "autonomous aircraft platform Germany",
      "civil aircraft to autonomous platform Germany",
      "autonomous platform Germany",
      "HPAA platform Germany",
      "optionally piloted aircraft platform Germany",
    ],
  },
  {
    id: "hpaa-faq",
    title: "Frequently Asked Questions: HPAA and Autonomous Aircraft Conversion",
    metaTitle: "HPAA FAQ — Autonomous Aircraft Conversion Questions Answered",
    metaDescription:
      "Answers to the most common questions about HPAA conversion, platform selection, mission capability, EASA certification, and procurement. KUM Services GmbH Konstanz.",
    targetKeywords: [
      "HPAA",
      "autonomous aircraft conversion",
      "how to convert civil aircraft to UAV",
      "EASA Part-145",
      "special mission aircraft for sale",
      "civil aircraft to autonomous platform",
      "aircraft conversion company Europe",
    ],
  },
];
