import type { Metadata } from "next";
import { env } from "@/app/env";
import { siteData } from "@/data/siteData";
import { buildPageMetadataFromSeoBlockId } from "./seo/buildSeoMetadata";
import { collectAllSeoMetaKeywords, getSeoMetaById } from "./seo/helpers";
import { absoluteUrl } from "./absoluteUrl";
import { getSiteUrl } from "./siteUrl";

const appName = env.NEXT_PUBLIC_APP_NAME;

/**
 * Off-page meta description only (Google/OG/Twitter, JSON-LD). Does not change visible copy in site-content.json.
 * Homepage `<title>` stays brand-facing via `buildRootMetadata` (`titleDefault`); query phrases belong here and in `metaDescription` blocks.
 */
export function getSeoRootDescription(): string {
  return [
    "HPAA (High Performance Autonomous Aircraft) — civil aircraft to autonomous platform Germany: KUM Services GmbH, Konstanz converts civil aircraft into high performance autonomous aircraft platforms for ISR, cargo, strike and special missions.",
    "Robot aircraft Germany and worldwide. Fast fielding, EASA Part-145 partner, worldwide support.",
  ]
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

export const siteKeywords: string[] = [
  "HPAA",
  "hpaa",
  "civil aircraft to autonomous platform Germany",
  "civil aircraft to autonomous platform",
  "civil aircraft conversion Germany",
  "robot aircraft Germany",
  "robot aircraft Konstanz",
  "aircraft robot Germany",
  "aircraft robot Konstanz",
  "robot aircraft",
  "aircraft robot",
  "autonomous aircraft robot",
  "HPAA Germany",
  "HPAA Konstanz",
  "high performance autonomous aircraft",
  "high performance autonomous aircraft conversion",
  "autonomous aircraft",
  "autonomous aircraft conversion",
  "autonomous aircraft platform",
  "civil aircraft conversion",
  "civil to military aircraft conversion",
  "civil registered aircraft",
  "aircraft retrofit",
  "aircraft modification",
  "aircraft mission conversion",
  "manned to unmanned conversion",
  "optionally piloted aircraft",
  "OPA",
  "remotely piloted aircraft",
  "RPA",
  "unmanned aerial vehicle",
  "UAV conversion",
  "large UAV",
  "Group 5 UAS",
  "tactical UAV",
  "MALE UAV",
  "medium altitude long endurance",
  "unmanned combat aerial vehicle",
  "UCAV",
  "combat UAV",
  "strike UAV",
  "weaponized UAV",
  "armed unmanned aircraft",
  "autonomous combat aircraft",
  "low observable UAV",
  "covert strike platform",
  "payload delivery aircraft",
  "payload drop system",
  "aerial payload delivery",
  "precision payload drop",
  "autonomous payload release",
  "weapons payload integration",
  "munitions delivery aircraft",
  "precision munitions delivery",
  "guided munitions drop",
  "air-to-ground payload",
  "standoff payload delivery",
  "parachute payload drop",
  "cargo drop mission",
  "aerial resupply unmanned",
  "combat payload aircraft",
  "strike payload platform",
  "autonomous bomb drop",
  "precision strike aircraft",
  "precision guided munitions platform",
  "PGM delivery",
  "kinetic effects platform",
  "effects delivery aircraft",
  "loitering munition carrier",
  "loitering munition platform",
  "loitering munition",
  "one-way attack UAV",
  "expendable UAV platform",
  "attritable aircraft",
  "attritable UAV",
  "autonomous strike mission",
  "air-launched effects",
  "ALE platform",
  "stand-in attack aircraft",
  "deep strike UAV",
  "war drone aircraft",
  "military robot aircraft",
  "combat robot aircraft",
  "autonomous war aircraft",
  "battlefield UAV",
  "combat autonomous system",
  "armed autonomous system",
  "autonomous weapons platform",
  "unmanned combat system",
  "lethal autonomous aircraft",
  "lethal UAV",
  "defence strike aircraft",
  "defense strike aircraft",
  "military strike platform",
  "offensive UAV platform",
  "close air support unmanned",
  "CAS unmanned aircraft",
  "interdiction UAV",
  "air interdiction platform",
  "suppression of enemy air defenses UAV",
  "SEAD UAV",
  "electronic warfare UAV",
  "EW payload aircraft",
  "jamming aircraft unmanned",
  "decoy aircraft UAV",
  "swarm capable aircraft",
  "manned unmanned teaming",
  "MUM-T aircraft",
  "loyal wingman concept",
  "wingman drone platform",
  "asymmetric warfare UAV",
  "grey zone operations aircraft",
  "low intensity conflict UAV",
  "mission systems integration",
  "ISR aircraft",
  "intelligence surveillance reconnaissance",
  "surveillance aircraft",
  "airborne surveillance",
  "special mission aircraft",
  "special mission conversion",
  "special operations aircraft",
  "EO/IR sensor integration",
  "electro-optical infrared",
  "SAR integration",
  "synthetic aperture radar aircraft",
  "signals intelligence aircraft",
  "SIGINT platform",
  "maritime patrol aircraft",
  "border surveillance aircraft",
  "airborne early warning",
  "cargo aircraft conversion",
  "aerial delivery system",
  "range extension aircraft",
  "cruise missile range extension",
  "cruise missile carrier aircraft",
  "air-launched cruise missile platform",
  "standoff weapon platform",
  "counter-UAS aircraft",
  "counter-drone aircraft",
  "anti-drone platform",
  "UAS defeat",
  "C-UAS platform",
  "drone interception aircraft",
  "kinetic counter-drone",
  "Cessna",
  "Cessna Citation",
  "Cessna Citation 525",
  "Cessna Citation CJ1",
  "Cessna Caravan",
  "Cessna 208",
  "Cessna 208B Grand Caravan",
  "Cessna 208 combat",
  "King Air",
  "King Air 350",
  "King Air 350 armed",
  "Beechcraft King Air",
  "Beechcraft",
  "Pilatus",
  "Pilatus PC-12",
  "PC-12 special mission",
  "PC-12 ISR",
  "PC-12 armed version",
  "C-130",
  "C-130J",
  "C-130J Super Hercules",
  "Lockheed Martin C-130",
  "turboprop aircraft conversion",
  "turbofan aircraft conversion",
  "business jet conversion",
  "light jet conversion",
  "twin turboprop conversion",
  "turboprop combat platform",
  "autonomous flight",
  "autonomous flight control",
  "flight control system",
  "autopilot integration",
  "avionics integration",
  "ground control station",
  "GCS",
  "datalink integration",
  "satcom integration",
  "sense and avoid",
  "detect and avoid",
  "DAA system",
  "beyond visual line of sight",
  "BVLOS operations",
  "fly-by-wire retrofit",
  "AI flight control",
  "machine learning flight system",
  "autonomous mission planning",
  "target acquisition system",
  "fire control system integration",
  "weapons release system",
  "stores management system",
  "autonomous targeting",
  "AI targeting aircraft",
  "EASA",
  "EASA Part-145",
  "EASA certified aircraft maintenance",
  "MRO partner",
  "maintenance repair overhaul",
  "EASA approved modification",
  "STC supplemental type certificate",
  "airworthiness",
  "civil registration aircraft",
  "no special flight permit",
  "dual use aircraft",
  "dual use aviation technology",
  "KUM Services GmbH",
  "KUM Services",
  "Konstanz",
  "Konstanz Germany",
  "Baden-Württemberg",
  "Bodensee",
  "Lake Constance",
  "aviation Konstanz",
  "aerospace Konstanz",
  "aviation company Germany",
  "aircraft conversion Germany",
  "aerospace Germany",
  "HPAA Germany",
  "Germany",
  "defence contractor Germany",
  "defense contractor Germany",
  "University of Stuttgart aviation",
  "German defence technology",
  "German defense technology",
  "German autonomous systems",
  "defence aviation",
  "military aircraft conversion",
  "government ISR platform",
  "NATO ISR",
  "NATO autonomous systems",
  "NATO UAS",
  "defence procurement",
  "defense procurement",
  "rapid capability acquisition",
  "affordable ISR platform",
  "low cost ISR",
  "quick reaction capability",
  "special mission OEM",
  "prime contractor aircraft",
  "system integrator aircraft",
  "defence ministry aircraft",
  "armed forces UAV",
  "military autonomous platform",
  "special forces aircraft",
  "SOF aircraft",
  "special operations forces UAV",
  "rapid deployment aircraft",
  "expeditionary UAV",
  "operational level autonomous aircraft",
  "buy autonomous aircraft",
  "purchase special mission aircraft",
  "autonomous aircraft supplier",
  "HPAA supplier",
  "HPAA manufacturer",
  "aircraft conversion contractor",
  "unmanned systems supplier Europe",
  "defence systems supplier Germany",
  "affordable combat UAV",
  "cost effective military UAV",
  "fast delivery military UAV",
  "quick fielding autonomous aircraft",
  "off the shelf UAV conversion",
  "turnkey UAV solution",
  "end to end aircraft conversion",
  "full system integration aircraft",
  "autonomous aircraft program",
  "scalable UAV solution",
  "multi-role autonomous aircraft",
  "autonomous aircraft quote",
  "request for proposal UAV",
  "RFP autonomous aircraft",
  "fast aircraft conversion",
  "on-site aircraft conversion",
  "short conversion time",
  "covert aircraft platform",
  "non-identifiable aircraft",
  "civil cover aircraft",
  "worldwide aircraft support",
  "worldwide spare parts",
  "proven airframe conversion",
  "low cost autonomous aircraft",
  "affordable unmanned conversion",
  "rapid fielding aircraft",
  "no ferry permit required",
  "civil registration military mission",
  "discreet mission aircraft",
  "low signature aircraft",
  "how to convert civil aircraft to UAV",
  "civil aircraft to autonomous platform",
  "buy special mission aircraft",
  "special mission aircraft for sale",
  "ISR aircraft for sale",
  "turboprop ISR platform",
  "HPAA platform provider",
  "autonomous aircraft integrator",
  "aircraft conversion company Europe",
  "aircraft modification company Germany",
  "unmanned systems integrator Europe",
  "convert business jet to drone",
  "armed drone aircraft for sale",
  "payload dropping drone aircraft",
  "military drone aircraft supplier",
  "autonomous strike aircraft supplier",
  "combat aircraft conversion company",
  "armed autonomous aircraft Europe",
  "payload delivery UAV supplier",
  "precision strike drone company",
  "autonomous aircraft for defence",
  "autonomous aircraft for defense",
  "unmanned combat aircraft Europe",
  "war drone supplier Europe",
  "military robot aircraft supplier",
  "combat drone aircraft conversion",
];


const defaultOgImage = absoluteUrl("/theme/hpaa9.jpeg");

/** Default + template for the whole site (segment pages override title/description). */
export function buildRootMetadata(): Metadata {
  const base = getSiteUrl();
  const metadataBase = new URL(base.endsWith("/") ? base : `${base}/`);

  /** Include location from brand for local/geo-related queries (e.g. aircraft + Konstanz). */
  const titleDefault = `${appName} · ${siteData.brand.name} · ${siteData.brand.tagline}`;
  const defaultDescription = getSeoRootDescription();
  const overview = getSeoMetaById("hpaa-overview");
  const rootDescription = overview?.metaDescription ?? defaultDescription;
  const rootKeywords = Array.from(new Set([...siteKeywords, ...collectAllSeoMetaKeywords()]));

  return {
    metadataBase,
    title: {
      default: titleDefault,
      template: `%s · ${appName}`,
    },
    description: rootDescription,
    keywords: rootKeywords,
    applicationName: appName,
    authors: [{ name: siteData.brand.name, url: base }],
    creator: siteData.brand.name,
    publisher: siteData.brand.name,
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
    alternates: {
      canonical: absoluteUrl("/"),
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-snippet": -1,
        "max-image-preview": "large",
        "max-video-preview": -1,
      },
    },
    verification: {
      google: "h2Ewg-tRNzTwDdnNLGtHKYI9kavgozjWxB7BYM_xQa0",
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url: absoluteUrl("/"),
      siteName: appName,
      title: titleDefault,
      description: rootDescription,
      images: [
        {
          url: defaultOgImage,
          width: 1200,
          height: 630,
          alt: `${siteData.brand.name} — ${siteData.brand.tagline}`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: titleDefault,
      description: rootDescription,
      images: [defaultOgImage],
    },
    category: "technology",
    other: {
      google: "notranslate",
    },
  };
}

/** Pre-built metadata for hash-redirect routes (unique URLs for crawlers and sharing). */
export const segmentMetadata = {
  aircraft: buildPageMetadataFromSeoBlockId("hpaa-platform-guide", "/aircraft"),
  applications: buildPageMetadataFromSeoBlockId("isr-surveillance-aircraft", "/applications", {
    extraKeywordBlockIds: ["payload-delivery-aircraft", "counter-uas-aircraft"],
  }),
  whyUs: buildPageMetadataFromSeoBlockId("hpaa-vs-purpose-built", "/why-us"),
  partners: buildPageMetadataFromSeoBlockId("autonomous-flight-control", "/partners"),
  contact: buildPageMetadataFromSeoBlockId("defence-procurement-hpaa", "/contact"),
} as const;
