# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build hpaa
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          APP_SECRET: Thisisshortsecretekey
          CI: true
          CONTACT_FROM_EMAIL: HPAA Website <info@kum-trading.consulting>HPAA Website <info@kum-trading.consulting>
          CONTACT_TO_EMAIL: info@kum-trading.consulting
          NEXT_PUBLIC_APP_NAME: HPAA
          SITE_URL: ${{ inputs.site-url }}
          SMTP_HOST: smtp.ionos.de
          SMTP_PASS: Kum12345!?
          SMTP_PASSWORD: Kum12345!?
          SMTP_PORT: 587
          SMTP_SECURE: false
          SMTP_USER: info@kum-trading.consulting
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: a11b7f3d-89b1-41a0-8238-0b04dfe3ed2f
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/hpaa/config.yaml
          action: upload
